# Generated by Django 2.1.5 on 2019-09-09 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_auto_20190610_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='like_cnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='like',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like', to='community.Post'),
        ),
    ]
