# Generated by Django 2.1.5 on 2019-09-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_auto_20190909_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.ImageField(default=None, upload_to='media/%Y/%m/%d'),
        ),
    ]
