# Generated by Django 2.1.5 on 2019-09-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_post_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.ImageField(default=None, null=True, upload_to='media/%Y/%m/%d'),
        ),
    ]
