# Generated by Django 2.1.5 on 2019-10-05 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_auto_20190928_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='like_cnt',
        ),
    ]
