# Generated by Django 2.1.5 on 2019-06-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_menu', models.CharField(max_length=1024)),
                ('faculty_menu', models.CharField(max_length=1024)),
            ],
        ),
    ]
