# Generated by Django 2.1.5 on 2019-09-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant_data',
            old_name='student_menu',
            new_name='ddoock',
        ),
        migrations.AddField(
            model_name='restaurant_data',
            name='il',
            field=models.CharField(default=1, max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant_data',
            name='noodle',
            field=models.CharField(default=12, max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant_data',
            name='rice',
            field=models.CharField(default=0, max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant_data',
            name='yang',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
    ]
