# Generated by Django 2.1.5 on 2019-10-11 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20190910_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant_data',
            old_name='ddoock',
            new_name='menu',
        ),
        migrations.RemoveField(
            model_name='restaurant_data',
            name='faculty_menu',
        ),
        migrations.RemoveField(
            model_name='restaurant_data',
            name='il',
        ),
        migrations.RemoveField(
            model_name='restaurant_data',
            name='noodle',
        ),
        migrations.RemoveField(
            model_name='restaurant_data',
            name='rice',
        ),
        migrations.RemoveField(
            model_name='restaurant_data',
            name='yang',
        ),
    ]
