# Generated by Django 2.1.5 on 2019-10-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20191011_1909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant_data',
            old_name='menu',
            new_name='ddoock',
        ),
        migrations.AddField(
            model_name='restaurant_data',
            name='faculty_menu',
            field=models.CharField(default=1234, max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant_data',
            name='il',
            field=models.CharField(default=1, max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant_data',
            name='noodle',
            field=models.CharField(default=1, max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant_data',
            name='rice',
            field=models.CharField(default=1, max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant_data',
            name='yang',
            field=models.CharField(default=1, max_length=1024),
            preserve_default=False,
        ),
    ]
