# Generated by Django 2.1.5 on 2019-04-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tu_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tu_id', models.CharField(max_length=50)),
                ('tu_password', models.CharField(max_length=50)),
                ('first_day', models.CharField(max_length=10)),
                ('second_day', models.CharField(max_length=10)),
                ('apply_text', models.TextField()),
            ],
        ),
    ]
