# Generated by Django 2.1.5 on 2019-09-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0003_remove_tu_data_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='tu_data',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
