# Generated by Django 2.1.5 on 2019-09-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0004_tu_data_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tu_data',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
