# Generated by Django 2.1.5 on 2019-09-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0005_auto_20190909_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tu_data',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
